### ISSUE TITLE
Reflecting changes after modifying data on page's Controllers.

### ISSUE THREAD

**Issue by JorgeAlvarez21** [JorgeAlvarez21/Dashboard-Flet#1]
A bit stuck trying to achieve this, I'm using Pandas DataFrame and I'm iterating through this one to create ft.Containers inside Columns for all the entries. I'm able to successfully display this data on the right Format, my approach might not be the best but it's mostly experimental.
Though getting the data onto the page seems to work fine, I cannot seem to find the right way to update any modifications I apply. -> Deletion, Sorting, Updating, etc.

I recreated an example of this inside .Dashboard-Flet/tests/test.py
The click of the button is successfully removing the chosen rows, but the page does not get updated to show this.

I tried with ft.ListViews, updating the Column's controllers and also updating the page. Any help/suggestions would be appreciated

https://github.com/JorgeAlvarez21/Dashboard-Flet/blob/b8f2e7cba070abb939f9c55fd684fa084f7909aa/tests/test.py#L64

**Comment by JorgeAlvarez21** [comment]
Hi @FeodorFitsner,

Do you think you can help me with this?

**Comment by FeodorFitsner** [comment]
Will take a look!
